properties([parameters([booleanParam(defaultValue: false, description: '', name: 'isRelease')])])

node("dockerhost1") {

    stage("checkout") {
        checkout scm
    } 
       
    stage("build") {
        buildMaven()
    }

    stage("changelog") {
        pac()
    }

    stage("release") {
        if(!params?.isRelease) {
            echo "Release build is not enabled"
        } else {
            echo "Release build enabled. Running release."
            releaseMaven()
        }
    }
}